name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn sentence-transformers scikit-learn beautifulsoup4 requests pandas numpy
        pip install pytest flake8
    
    - name: Lint with flake8
      run: |
        # Stop build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Treat all other issues as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test search engine components
      run: |
        # Test basic imports
        python -c "import api.main; print('✅ API imports OK')"
        python -c "from api.cached_search import search_engine; print('✅ Search engine OK')"
        
        # Test data files exist
        python -c "import json; data=json.load(open('data/search_index.json')); print(f'✅ {len(data)} blogs loaded')"
    
    - name: Validate quality (dry run)
      run: |
        python scripts/validate_quality.py --dry-run

  docker:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      run: |
        docker build -t personal-blog-search:latest .
        
    - name: Test Docker image
      run: |
        # Test that the image builds and starts
        docker run --rm -d -p 8001:8001 --name test-container personal-blog-search:latest
        sleep 10
        # Test health endpoint
        curl -f http://localhost:8001/api/health || exit 1
        docker stop test-container